server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.mail.ru
    port: 465
    username: danik-rebkovets@mail.ru
    password: 7FygKwezzLWKB6wWK8Ye
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true