create table windows
(
    id           int generated by default AS IDENTITY primary key,
    model        varchar,
    width        int,
    height       int,
    price        int,
    manufacturer varchar,
    availability boolean
)